{
 "title": "Data Quality Platform",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "table", "label": "Select table", "query": { "query": "label_values(table)" } }
  ]
 },
 "panels": [
  { "title": "Data Profiling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Record Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "AutoDQ_DataProfiling{name=\"Size\", table=\"$table\"} and on (job) push_time_seconds >= time()-(${__interval_ms}/1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Column",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (AutoDQ_DataProfiling{table=\"$table\", entity=\"Column\", name=\"Completeness\"} and on (job) push_time_seconds >= time()-(${__interval_ms}/1000) ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Numeric Type Column",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (AutoDQ_DataProfiling{table=\"$table\", entity=\"Column\", name=\"Maximum\"} and on (job) push_time_seconds >= time()-(${__interval_ms}/1000) ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "String Type Column",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (AutoDQ_DataProfiling{table=\"$table\", entity=\"Column\", name=\"MaxLength\"} and on (job) push_time_seconds >= time()-(${__interval_ms}/1000) ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max null percent in a column",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max (1 - AutoDQ_DataProfiling{name=\"Completeness\", table=\"$table\"} and on (job) push_time_seconds >= time()-(${__interval_ms}/1000))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distinct Account",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AutoDQ_DataProfiling{name=\"ApproxCountDistinct\", table=\"$table\"} and on (job) push_time_seconds >= time()-(${__interval_ms}/1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Null Percent",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-AutoDQ_DataProfiling{name=\"Completeness\", table=\"$table\"} and on (job) push_time_seconds >= time()-(${__interval_ms}/1000)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Minimum Length of String Type Column",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AutoDQ_DataProfiling{name=~\"MinLength\", table=\"$table\"} and on (job) push_time_seconds >= time()-(${__interval_ms}/1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Maximum Length of String Type Column",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AutoDQ_DataProfiling{name=~\"MaxLength\", table=\"$table\"} and on (job) push_time_seconds >= time()-(${__interval_ms}/1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Minimum value of Numeric Type Column",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AutoDQ_DataProfiling{name=~\"Minimum\", table=\"$table\"} and on (job) push_time_seconds >= time()-(${__interval_ms}/1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Maximum value of Numeric Type Column",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AutoDQ_DataProfiling{name=~\"Maximum\", table=\"$table\"} and on (job) push_time_seconds >= time()-(${__interval_ms}/1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mean value of Numeric Type Column",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AutoDQ_DataProfiling{name=~\"Mean\", table=\"$table\"} and on (job) push_time_seconds >= time()-(${__interval_ms}/1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sum value of Numeric Type Column",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AutoDQ_DataProfiling{name=~\"Sum\", table=\"$table\"} and on (job) push_time_seconds >= time()-(${__interval_ms}/1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Anomaly Detection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "ROC_AUC",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "AutoDQ_AnomalyDetection{metric=\"roc_auc\", table=\"$table\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SHAP",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AutoDQ_AnomalyDetection{metric_type=\"SHAP\",table=\"$table\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Constraints Verification Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }
  },
  {
   "title": "Constraints Verification Result",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "AutoDQ_ConstraintsVerification{table=\"$table\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}